version: "3.7"

services:
  node-red-core:
    container_name: node-red-antiled77
    build:
      context: .
      dockerfile: ./nodered-core.Dockerfile
    env_file: .env
    ports:
      - "1881:1881"
    networks:
      - antilednet
    volumes:
      - ./node-red-core:/data 
    restart: always

volumes:
  node-red-core:

networks:
  antilednet: 